In [6]:
#Пустой кортеж:
()

()

In [7]:
# кортеж из элементов типа String:
favoritelang = ( "Python", "Julia", "R")

("Python", "Julia", "R")

In [9]:
# кортеж из целых чисел:
x1 = (1, 2, 3)

(1, 2, 3)

In [10]:
# кортеж из элементов разных типов:
x2 = ( 1, 2.0, "tmp")

(1, 2.0, "tmp")

In [11]:
# именованный кортеж:
x3 = (a=2, b=1+2)

(a = 2, b = 3)

In [12]:
# длина кортежа x2:
length(x2)

3

In [14]:
# обратиться к элементам кортежа x2:
x2[1], x2[2], x2[3]

(1, 2.0, "tmp")

In [15]:
# произвести какую-либо операцию (сложение)
# с вторым и третьим элементами кортежа x1:
c = x1[2] + x1[3]

5

In [16]:
# обращение к элементам именованного кортежа x3:
x3.a, x3.b, x3[2]

(2, 3, 3)

In [18]:
# проверка вхождения элементов tmp и 0 в кортеж x2
# (два способа обращения к методу in()):
in("tmp", x2), 0 in x2

(true, false)

In [19]:
# создать словарь с именем phonebook:
phonebook = Dict("Иванов И.И." => ("867-5309","333-5544"), "Бухгалтерия" => "555-2368")

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [20]:
# вывести ключи словаря:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Бухгалтерия"
  "Иванов И.И."

In [21]:
# вывести значения элементов словаря:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "555-2368"
  ("867-5309", "333-5544")

In [22]:
# вывести заданные в словаре пары "ключ - значение":
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [23]:
# проверка вхождения ключа в словарь:
haskey(phonebook, "Иванов И.И.")

true

In [24]:
# добавить элемент в словарь:
phonebook["Сидоров П.С."] = "555-3344"

"555-3344"

In [26]:
# удалить ключ и связанные с ним значения из словаря
pop!(phonebook, "Иванов И.И.")

("867-5309", "333-5544")

In [29]:
# Объединение словарей (функция merge()):
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);
merge(a, b), merge(b,a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

In [30]:
# создать множество из четырёх целочисленных значений:
A = Set([1, 3, 4, 5])

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [31]:
# создать множество из 11 символьных значений:
B = Set("abrakadabra")

Set{Char} with 5 elements:
  'a'
  'd'
  'r'
  'k'
  'b'

In [32]:
# проверка эквивалентности двух множеств:
S1 = Set([1,2]);
S2 = Set([3,4]);
issetequal(S1,S2)

false

In [33]:
S3 = Set([1,2,2,3,1,2,3,2,1]);
S4 = Set([2,3,1]);
issetequal(S3,S4)

true

In [34]:
# объединение множеств:
C = union(S1,S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [35]:
# пересечение множеств:
D = intersect(S1,S3)

Set{Int64} with 2 elements:
  2
  1

In [36]:
# разность множеств:
E = setdiff(S3,S1)

Set{Int64} with 1 element:
  3

In [37]:
# проверка вхождения элементов одного множества в другое:
issubset(S1,S4)

true

In [38]:
# добавление элемента в множество:
push!(S4, 99)

Set{Int64} with 4 elements:
  2
  99
  3
  1

In [39]:
# удаление последнего элемента множества:
pop!(S4)

2

In [40]:
# создание пустого массива с абстрактным типом:
empty_array_1 = []

Any[]

In [43]:
# создание пустого массива с конкретным типом:
empty_array_2 = (Integer)[]

Integer[]

In [44]:
empty_array_3 = (Float64)[]

Float64[]

In [45]:
# вектор-столбец:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [46]:
# вектор-строка:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [47]:
# многомерные массивы (матрицы):
A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]
B = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [48]:
# одномерный массив из 8 элементов (массив $1 \times 8$)
# со значениями, случайно распределёнными на интервале [0, 1):
c = rand(1,8)

1×8 Matrix{Float64}:
 0.256226  0.25554  0.784568  0.927575  0.986676  0.33549  0.271116  0.72746

In [50]:
# многомерный массив $2 \times 3$ (2 строки, 3 столбца) элементов
# со значениями, случайно распределёнными на интервале [0, 1):
C = rand(2,3);

In [51]:
# трёхмерный массив:
D = rand(4, 3, 2)


4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.512968  0.526186  0.961304
 0.853289  0.152252  0.859678
 0.952187  0.24875   0.946399
 0.48737   0.751777  0.45694

[:, :, 2] =
 0.906144  0.438187   0.732813
 0.536162  0.0129409  0.789865
 0.978429  0.786002   0.18819
 0.962649  0.131996   0.302249

In [52]:
# массив из квадратных корней всех целых чисел от 1 до 10:
roots = [sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

In [53]:
# массив с элементами вида 3*x^2,
# где x - нечётное число от 1 до 9 (включительно)
ar_1 = [3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [54]:
# массив квадратов элементов, если квадрат не делится на 5 или 4:
ar_2=[i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

In [55]:
# одномерный массив из пяти единиц:
ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [56]:
# двумерный массив 2x3 из единиц:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [57]:
# одномерный массив из 4 нулей:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [58]:
# заполнить массив 3x2 цифрами 3.5
fill(3.5,(3,2))

3×2 Matrix{Float64}:
 3.5  3.5
 3.5  3.5
 3.5  3.5

In [59]:
# заполнение массива посредством функции repeat():
repeat([1,2],3,3)
repeat([1 2],3,3)

3×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 1  2  1  2  1  2

In [60]:
# преобразование одномерного массива из целых чисел от 1 до 12
# в двумерный массив 2x6
a = collect(1:12)
b = reshape(a,(2,6))

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [61]:
# транспонирование
b'

6×2 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [62]:
# транспонирование
с = transpose(b)

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [63]:
# массив 10x5 целых чисел в диапазоне [10, 20]:
ar = rand(10:20, 10, 5)

10×5 Matrix{Int64}:
 12  10  13  13  11
 15  18  14  14  14
 19  10  11  18  13
 16  11  15  10  20
 11  10  10  18  16
 14  20  13  19  10
 20  19  11  18  13
 20  19  11  20  11
 14  18  16  12  15
 13  17  11  18  19

In [64]:
# выбор всех значений строки в столбце 2:
ar[:, 2]

10-element Vector{Int64}:
 10
 18
 10
 11
 10
 20
 19
 19
 18
 17

In [65]:
# выбор всех значений в столбцах 2 и 5:
ar[:, [2, 5]]

10×2 Matrix{Int64}:
 10  11
 18  14
 10  13
 11  20
 10  16
 20  10
 19  13
 19  11
 18  15
 17  19

In [66]:
# все значения строк в столбцах 2, 3 и 4:
ar[:, 2:4]

10×3 Matrix{Int64}:
 10  13  13
 18  14  14
 10  11  18
 11  15  10
 10  10  18
 20  13  19
 19  11  18
 19  11  20
 18  16  12
 17  11  18

In [67]:
# значения в строках 2, 4, 6 и в столбцах 1 и 5:
ar[[2, 4, 6], [1, 5]]

3×2 Matrix{Int64}:
 15  14
 16  20
 14  10

In [68]:
# значения в строке 1 от столбца 3 до последнего столбца:
ar[1, 3:end]

3-element Vector{Int64}:
 13
 13
 11

In [69]:
# сортировка по строкам:
sort(ar,dims=1)

10×5 Matrix{Int64}:
 11  10  10  10  10
 12  10  11  12  11
 13  10  11  13  11
 14  11  11  14  13
 14  17  11  18  13
 15  18  13  18  14
 16  18  13  18  15
 19  19  14  18  16
 20  19  15  19  19
 20  20  16  20  20

In [70]:
# сортировка по столбцам:
sort(ar,dims=2)

10×5 Matrix{Int64}:
 10  11  12  13  13
 14  14  14  15  18
 10  11  13  18  19
 10  11  15  16  20
 10  10  11  16  18
 10  13  14  19  20
 11  13  18  19  20
 11  11  19  20  20
 12  14  15  16  18
 11  13  17  18  19

In [71]:
# поэлементное сравнение с числом
# (результат - массив логических значений):
ar .> 14

10×5 BitMatrix:
 0  0  0  0  0
 1  1  0  0  0
 1  0  0  1  0
 1  0  1  0  1
 0  0  0  1  1
 0  1  0  1  0
 1  1  0  1  0
 1  1  0  1  0
 0  1  1  0  1
 0  1  0  1  1

In [76]:
# возврат индексов элементов массива, удовлетворяющих условию:
findall(ar .> 14)

23-element Vector{CartesianIndex{2}}:
 CartesianIndex(2, 1)
 CartesianIndex(3, 1)
 CartesianIndex(4, 1)
 CartesianIndex(7, 1)
 CartesianIndex(8, 1)
 CartesianIndex(2, 2)
 CartesianIndex(6, 2)
 CartesianIndex(7, 2)
 CartesianIndex(8, 2)
 CartesianIndex(9, 2)
 CartesianIndex(10, 2)
 CartesianIndex(4, 3)
 CartesianIndex(9, 3)
 CartesianIndex(3, 4)
 CartesianIndex(5, 4)
 CartesianIndex(6, 4)
 CartesianIndex(7, 4)
 CartesianIndex(8, 4)
 CartesianIndex(10, 4)
 CartesianIndex(4, 5)
 CartesianIndex(5, 5)
 CartesianIndex(9, 5)
 CartesianIndex(10, 5)

In [73]:
A = Set([0, 3, 4, 9])

Set{Int64} with 4 elements:
  0
  4
  9
  3

In [74]:
B = Set([1, 3, 4, 7])

Set{Int64} with 4 elements:
  4
  7
  3
  1

In [75]:
C = Set([0, 1, 2, 4, 7, 8, 9])

Set{Int64} with 7 elements:
  0
  4
  7
  2
  9
  8
  1

In [77]:
#𝑃 = 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐶 ∪ 𝐵 ∩ C
# объединение множеств: C=union(S1,S2)
# пересечение множеств: D = intersect(S1,S3)

In [79]:
d = intersect(A, B)

Set{Int64} with 2 elements:
  4
  3

In [80]:
f = intersect( A, C)

Set{Int64} with 3 elements:
  0
  4
  9

In [82]:
e = intersect(B, C)

Set{Int64} with 3 elements:
  4
  7
  1

In [83]:
p = union(d, d, f, e)

Set{Int64} with 6 elements:
  0
  4
  7
  9
  3
  1

In [84]:
#Приведите свои примеры с выполнением операций над множествами элементов разныхтипов

In [86]:
A = Set([1, 2, 3, 4])

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [87]:
B = Set(["a", "b", "c", "d"])

Set{String} with 4 elements:
  "c"
  "b"
  "a"
  "d"

In [89]:
# проверка эквивалентности двух множеств:
issetequal(A, B)

false

In [90]:
# объединение множеств:
C = union(A, B)

Set{Any} with 8 elements:
  "d"
  4
  "c"
  2
  "b"
  3
  1
  "a"

In [91]:
# пересечение множеств:
D = intersect(A, B)

Set{Int64}()

In [92]:
# разность множеств:
E = setdiff(A, B)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [93]:
# проверка вхождения элементов одного множества в другое:
issubset(A,B)

false

In [99]:
# добавление элемента в множество:
push!(B, "99")

Set{String} with 5 elements:
  "c"
  "99"
  "b"
  "a"
  "d"

In [95]:
# удаление последнего элемента множества:
pop!(A)

4

3.1) массив (1, 2, 3, … 𝑁 − 1, 𝑁 ), 𝑁 выберите больше 20;


In [100]:
n = 22

22

In [108]:
a_3_1 = collect(1:n)
print(a_3_1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

3.2) массив (𝑁, 𝑁 − 1 … , 2, 1), 𝑁 выберите больше 20;


In [111]:
a_3_2 = [n - i + 1 for i in 1:n]
print(a_3_2)

[22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

3.3) массив (1, 2, 3, … , 𝑁 − 1, 𝑁, 𝑁 − 1, … , 2, 1), 𝑁 выберите больше 20

In [126]:
a_3_3 = ones(n*2-1)
for i in 1:n
    a_3_3[i] = i
    a_3_3[n*2-i] = i
end
print(a_3_3)

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 21.0, 20.0, 19.0, 18.0, 17.0, 16.0, 15.0, 14.0, 13.0, 12.0, 11.0, 10.0, 9.0, 8.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 1.0]

3.4) массив с именем tmp вида (4, 6, 3);

In [161]:
tmp = [4, 6, 3]
print(tmp)

[4, 6, 3]

3.5) массив, в котором первый элемент массива tmp повторяется 10 раз;

In [162]:
tmp_3_5 = repeat([tmp[1]],10)
print(tmp_3_5)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]

3.6) массив, в котором все элементы массива tmp повторяются 10 раз;

In [193]:
n = length(tmp)
tmp_3_6_1 = []
tmp_3_6 =(Integer)[]
for i in 1:n
    tmp_3_6_1 = repeat([tmp[i]],10)
    append!(tmp_3_6, tmp_3_6_1)
end
print(tmp_3_6)

Integer[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

3.7)массив, в котором первый элемент массива tmp встречается 11 раз, второй элемент
— 10 раз, третий элемент — 10 раз;

In [194]:
tmp_3_7 = [fill(tmp[1], (11)); fill(tmp[2],(10)); fill(tmp[3],(10))]
print(tmp_3_7)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

3.8) массив, в котором первый элемент массива tmp встречается 10 раз подряд, второй
элемент — 20 раз подряд, третий элемент — 30 раз подряд;

In [196]:
tmp_3_8 = [fill(tmp[1], (10)); fill(tmp[2],(20)); fill(tmp[3],(30))]
print(tmp_3_8)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

3.10) вектор значений 𝑦 = 𝑒^𝑥
cos(𝑥) в точках 𝑥 = 3, 3.1, 3.2, … , 6, найдите среднее
значение 𝑦;


In [197]:
num_3_10 = [exp(i)*cos(i) for i in 3:0.1:6]
sum = 0
for i in 1:length(num_3_10)
    sum += num_3_10[i]
end
print(sum/length(num_3_10))

53.11374594642971

3.11) вектор вида (𝑥𝑖, 𝑦𝑗), 𝑥 = 0.1, 𝑖 = 3, 6, 9, … , 36, 𝑦 = 0.2, 𝑗 = 1, 4, 7, , 34;

In [199]:
x = 0.1
y = 0.2
num_11 = []
i = 3
for j in 1:3:34
    append!(num_11,[(x^i,y^j)])
    i += 3
end
print(num_11)

Any[(0.0010000000000000002, 0.2), (1.0000000000000004e-6, 0.0016000000000000003), (1.0000000000000005e-9, 1.2800000000000005e-5), (1.0000000000000006e-12, 1.0240000000000006e-7), (1.0000000000000009e-15, 8.192000000000005e-10), (1.000000000000001e-18, 6.5536000000000055e-12), (1.0000000000000012e-21, 5.2428800000000056e-14), (1.0000000000000014e-24, 4.194304000000005e-16), (1.0000000000000015e-27, 3.3554432000000048e-18), (1.0000000000000017e-30, 2.684354560000004e-20), (1.0000000000000018e-33, 2.1474836480000035e-22), (1.000000000000002e-36, 1.717986918400003e-24)]

3.12) вектор с элементами 2^𝑖/𝑖, 𝑖 = 1, 2, … , 𝑀, 𝑀 = 25;

In [200]:
M = 25
num_12 = [(2^i)/i for i in 1:M]
print(num_12)

[2.0, 2.0, 2.6666666666666665, 4.0, 6.4, 10.666666666666666, 18.285714285714285, 32.0, 56.888888888888886, 102.4, 186.1818181818182, 341.3333333333333, 630.1538461538462, 1170.2857142857142, 2184.5333333333333, 4096.0, 7710.117647058823, 14563.555555555555, 27594.105263157893, 52428.8, 99864.38095238095, 190650.18181818182, 364722.0869565217, 699050.6666666666, 1.34217728e6]

3.13) вектор вида (”fn1”, ”fn2”, …, ”fnN”), 𝑁 = 30;

In [201]:
N = 30
num_13 = ["fn$i" for i in 1:N]
print(num_13)

["fn1", "fn2", "fn3", "fn4", "fn5", "fn6", "fn7", "fn8", "fn9", "fn10", "fn11", "fn12", "fn13", "fn14", "fn15", "fn16", "fn17", "fn18", "fn19", "fn20", "fn21", "fn22", "fn23", "fn24", "fn25", "fn26", "fn27", "fn28", "fn29", "fn30"]

3.14) векторы 𝑥 = (𝑥1, 𝑥2, … , 𝑥𝑛) и 𝑦 = (𝑦1, 𝑦2, … , 𝑦𝑛) целочисленного типа длины 𝑛 = 250 как случайные выборки из совокупности 0, 1, … , 999; на его  основе:

In [202]:
n = 250
x_14 = rand(0:999, n)
y_14 = rand(0:999, n)

250-element Vector{Int64}:
 164
 836
 528
  18
 606
 135
 753
 967
 967
 986
 399
 180
 804
   ⋮
  42
 676
 335
 260
 645
 256
 219
 508
 313
 943
 558
 621

– сформируйте вектор (𝑥1 + 2𝑥2 − 𝑥3, 𝑥2 + 2𝑥3 − 𝑥4, … , 𝑥𝑛−2 + 2𝑥𝑛−1 − 𝑥𝑛);

In [209]:
vect_2= [x_14[i-2] + 2*x_14[i-1] - x_14[i] for i in 3:250]

248-element Vector{Int64}:
 1124
 1002
 1802
  532
 1502
 1918
  119
  738
 2664
  908
 -670
  607
 1795
    ⋮
  533
 1332
  967
  973
 2248
 1594
  526
  281
  641
 1093
 1748
 2557

– сформируйте вектор (𝑦2 − 𝑥1, … , 𝑦𝑛 − 𝑥𝑛−1);

In [210]:
vect_1 = [y_14[i] - x_14[i-1]  for i in 2:n]

249-element Vector{Int64}:
  512
 -149
 -536
 -177
 -183
 -134
  377
  818
  217
 -550
  177
  757
 -113
    ⋮
 -272
  -71
 -141
 -472
 -322
 -162
   10
  198
 -235
  178
 -427
 -366

– сформируйте вектор

In [211]:
vect_3 = [sin(y_14[i])/cos(x_14[i+1]) for i in 1:n-1]

249-element Vector{Float64}:
 -45.014520279588666
   0.6998480593510994
  -0.28640827441532885
   0.9811765005975805
   0.67082301065147
   0.10853224328311645
   3.717429793472862
   0.7434754805575975
  -0.590083386579091
   0.44852020901361206
   0.017869022400804575
  -0.8903273518441155
  -0.24658480055663878
   ⋮
   1.2019369185654527
 -18.822172325347037
   0.5291548566030667
   1.1142295549053944
  -0.6930171105600276
   9.844835812087991
   1.9019939576209657
  -3.8290976518675124
 -36.34478106537391
  -8.29592099108593
   0.5815070743494083
  -0.9405038938622042

– вычислите

In [219]:
sum = 0
for i in 1:n-1
    sum += exp(-x_14[i+1])/(x_14[i]+10)
end
print(sum)

0.00020272966863897623

выберите элементы вектора 𝑦, значения которых больше 600, и выведите на
экран; определите индексы этих элементов;

In [224]:
for i in i:n
    if y_14[i] > 600
        println("Значение: ", y_14[i], " Индек: $i")
    end
end

Значение: 605 Индек: 40
Значение: 618 Индек: 43
Значение: 966 Индек: 45
Значение: 916 Индек: 47
Значение: 936 Индек: 48
Значение: 831 Индек: 51
Значение: 931 Индек: 53
Значение: 788 Индек: 56
Значение: 604 Индек: 57
Значение: 779 Индек: 59
Значение: 818 Индек: 62
Значение: 644 Индек: 65
Значение: 873 Индек: 67
Значение: 960 Индек: 69
Значение: 914 Индек: 71
Значение: 682 Индек: 74
Значение: 967 Индек: 75
Значение: 893 Индек: 79
Значение: 720 Индек: 80
Значение: 744 Индек: 81
Значение: 973 Индек: 82
Значение: 881 Индек: 83
Значение: 943 Индек: 87
Значение: 981 Индек: 89
Значение: 967 Индек: 92
Значение: 607 Индек: 94
Значение: 657 Индек: 95
Значение: 898 Индек: 97
Значение: 914 Индек: 98
Значение: 920 Индек: 102
Значение: 887 Индек: 105
Значение: 647 Индек: 106
Значение: 666 Индек: 107
Значение: 969 Индек: 108
Значение: 744 Индек: 109
Значение: 878 Индек: 110
Значение: 980 Индек: 112
Значение: 741 Индек: 115
Значение: 670 Индек: 117
Значение: 776 Индек: 121
Значение: 762 Индек: 123
Знач

определите значения вектора 𝑥, соответствующие значениям вектора 𝑦, значения которых больше 600 (под соответствием понимается расположение на
аналогичных индексных позициях);

In [226]:
for i in i:n
    if x_14[i] > 600 && y_14[i] > 600
        println(x_14[i])
    end
end

713
972
744
643
884
972
868
668
742
771
710
868
777
693
882
868
727
924
831
803
639
920
784
868
663
806
767
821
727
703
841
949
859
937
650
979
910
688
652
985


сформируйте вектор

In [228]:
sum = 0
for i in 1:n
    sum += x_14[i]
end
med = sum/n
v = [(abs(x_14[i] - med))^(1/2) for i in i:n]

212-element Vector{Float64}:
 17.622599127257025
 13.731569466015166
 10.979799633873109
  5.343781432656097
 21.155519374385495
 19.405050888879423
  5.517608177462401
 15.081246632821836
  5.249380915879514
 14.817422177963346
  9.775274932195003
 13.432944576674169
 10.888342389914088
  ⋮
 14.918310896344801
  6.960172411657628
 14.406803948135064
 21.037014997380215
 10.317170154649965
 17.760743227691794
 14.64390658260288
  4.853452379492359
 15.509867826645076
 21.46056849200412
 21.507115101751793
 11.065441699272558

определите, сколько элементов вектора 𝑦 отстоят от максимального значения не
более, чем на 200;

In [231]:
count = 0
max = maximum(y_14[i])
for i in 1:n
    if max - y_14[i] <= 200
        count += 1
    end
end
print(count)

250

– определите, сколько чётных и нечётных элементов вектора 𝑥;

In [233]:
count_chet = 0
count_nechet = 0
for i in 1:n 
    if x_14[i] %2 == 0
        count_chet += 1
    end
    if x_14[i] %2 == 1
        count_nechet += 1
    end
end
println("Четных: ", count_chet)
println("Нечетных: ", count_nechet)

Четных: 125
Нечетных: 125


определите, сколько элементов вектора 𝑥 кратны 7

In [234]:
sev_count = 0
for i in 1:n 
    if x_14[i] %7 == 0
        sev_count += 1
    end
end
println("Кратных семи: ", sev_count)

Кратных семи: 33


– отсортируйте элементы вектора 𝑥 в порядке возрастания элементов вектора 𝑦;

– выведите элементы вектора 𝑥, которые входят в десятку наибольших (top-10)?

In [238]:
sorted_x = sort!(x_14, rev = true)
print(sorted_x[1:10])

[992, 990, 987, 985, 985, 979, 979, 974, 973, 972]

сформируйте вектор, содержащий только уникальные (неповторяющиеся) элементы вектора x

In [239]:
uniq_x = unique(x_14)
print(uniq_x)

[992, 990, 987, 985, 979, 974, 973, 972, 967, 965, 949, 937, 930, 924, 920, 918, 916, 910, 901, 892, 887, 884, 882, 872, 871, 868, 864, 859, 841, 836, 835, 833, 831, 823, 821, 820, 808, 806, 803, 784, 783, 777, 776, 771, 769, 767, 765, 761, 760, 747, 744, 743, 742, 739, 736, 732, 730, 728, 727, 720, 713, 710, 703, 701, 696, 693, 688, 683, 680, 677, 668, 664, 663, 654, 652, 650, 645, 644, 643, 639, 632, 629, 620, 617, 604, 598, 594, 593, 591, 590, 586, 583, 581, 579, 570, 569, 568, 564, 563, 562, 558, 554, 553, 552, 548, 545, 541, 538, 537, 523, 516, 515, 505, 499, 498, 495, 494, 491, 490, 489, 488, 485, 482, 476, 475, 474, 469, 468, 444, 441, 437, 435, 432, 418, 414, 405, 402, 398, 378, 360, 356, 352, 349, 347, 346, 344, 343, 342, 334, 329, 328, 327, 326, 324, 318, 314, 310, 305, 303, 297, 291, 288, 279, 274, 270, 266, 258, 252, 251, 249, 246, 235, 234, 229, 224, 219, 215, 209, 208, 207, 202, 200, 195, 193, 190, 183, 179, 152, 149, 145, 144, 142, 128, 123, 120, 118, 116, 110, 101, 90, 

4. Создайте массив squares, в котором будут храниться квадраты всех целых чисел от 1
до 100

In [240]:
squares = [i^2 for i in 1:100]

100-element Vector{Int64}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

. Подключите пакет Primes (функции для вычисления простых чисел). Сгенерируйте
массив myprimes, в котором будут храниться первые 168 простых чисел. Определите
89-е наименьшее простое число. Получите срез массива с 89-го до 99-го элемента
включительно, содержащий наименьшие простые числа.

In [242]:
using Primes
myprimes = primes(1000)
print(length(myprimes))

168

In [243]:
print(myprimes[89])

461

In [244]:
print(myprimes[89:99])

[461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523]

6. Вычислите следующие выражения:

In [250]:
sum = 0
for i in 10:100
    sum += i^3 + 4i^2
end
print(sum)

26852735

In [251]:
M = 25
sum = 0
for i in 1:M
    sum += (2^i)/i + (3^i)/i^2
end
print(sum)

2.1291704368143802e9

In [254]:
k = 1
sum = 1
for i in 1:2:37
    k = k*(i+1)/(i+2) 
    sum += k
end
print(sum)

6.97634613789762